// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserPrefs.proto

package com.example.projectdemo.protobuf;

public final class UserPrefs {
  private UserPrefs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserPreferencesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserPreferences)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * String类型
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    java.lang.String getQuery();
    /**
     * <pre>
     * String类型
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <pre>
     * int类型 sint32
     * </pre>
     *
     * <code>int32 page_number = 2;</code>
     * @return The pageNumber.
     */
    int getPageNumber();

    /**
     * <pre>
     * long类型 sint64
     * </pre>
     *
     * <code>int64 result_per_page = 3;</code>
     * @return The resultPerPage.
     */
    long getResultPerPage();

    /**
     * <pre>
     * boolean类型
     * </pre>
     *
     * <code>bool age = 4;</code>
     * @return The age.
     */
    boolean getAge();

    /**
     * <pre>
     * double类型
     * </pre>
     *
     * <code>double student_name = 5;</code>
     * @return The studentName.
     */
    double getStudentName();

    /**
     * <pre>
     * float类型
     * </pre>
     *
     * <code>float student_fs = 6;</code>
     * @return The studentFs.
     */
    float getStudentFs();

    /**
     * <pre>
     * bytes类型
     * </pre>
     *
     * <code>bytes student_fs_dd = 7;</code>
     * @return The studentFsDd.
     */
    com.google.protobuf.ByteString getStudentFsDd();
  }
  /**
   * <pre>
   * 格式：字段类型 + 字段名称 + 字段编号 = 编号（唯一）
   * </pre>
   *
   * Protobuf type {@code UserPreferences}
   */
  public  static final class UserPreferences extends
      com.google.protobuf.GeneratedMessageLite<
          UserPreferences, UserPreferences.Builder> implements
      // @@protoc_insertion_point(message_implements:UserPreferences)
      UserPreferencesOrBuilder {
    private UserPreferences() {
      query_ = "";
      studentFsDd_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int QUERY_FIELD_NUMBER = 1;
    private java.lang.String query_;
    /**
     * <pre>
     * String类型
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The query.
     */
    @java.lang.Override
    public java.lang.String getQuery() {
      return query_;
    }
    /**
     * <pre>
     * String类型
     * </pre>
     *
     * <code>string query = 1;</code>
     * @return The bytes for query.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(query_);
    }
    /**
     * <pre>
     * String类型
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The query to set.
     */
    private void setQuery(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      query_ = value;
    }
    /**
     * <pre>
     * String类型
     * </pre>
     *
     * <code>string query = 1;</code>
     */
    private void clearQuery() {
      
      query_ = getDefaultInstance().getQuery();
    }
    /**
     * <pre>
     * String类型
     * </pre>
     *
     * <code>string query = 1;</code>
     * @param value The bytes for query to set.
     */
    private void setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      query_ = value.toStringUtf8();
    }

    public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
    private int pageNumber_;
    /**
     * <pre>
     * int类型 sint32
     * </pre>
     *
     * <code>int32 page_number = 2;</code>
     * @return The pageNumber.
     */
    @java.lang.Override
    public int getPageNumber() {
      return pageNumber_;
    }
    /**
     * <pre>
     * int类型 sint32
     * </pre>
     *
     * <code>int32 page_number = 2;</code>
     * @param value The pageNumber to set.
     */
    private void setPageNumber(int value) {
      
      pageNumber_ = value;
    }
    /**
     * <pre>
     * int类型 sint32
     * </pre>
     *
     * <code>int32 page_number = 2;</code>
     */
    private void clearPageNumber() {
      
      pageNumber_ = 0;
    }

    public static final int RESULT_PER_PAGE_FIELD_NUMBER = 3;
    private long resultPerPage_;
    /**
     * <pre>
     * long类型 sint64
     * </pre>
     *
     * <code>int64 result_per_page = 3;</code>
     * @return The resultPerPage.
     */
    @java.lang.Override
    public long getResultPerPage() {
      return resultPerPage_;
    }
    /**
     * <pre>
     * long类型 sint64
     * </pre>
     *
     * <code>int64 result_per_page = 3;</code>
     * @param value The resultPerPage to set.
     */
    private void setResultPerPage(long value) {
      
      resultPerPage_ = value;
    }
    /**
     * <pre>
     * long类型 sint64
     * </pre>
     *
     * <code>int64 result_per_page = 3;</code>
     */
    private void clearResultPerPage() {
      
      resultPerPage_ = 0L;
    }

    public static final int AGE_FIELD_NUMBER = 4;
    private boolean age_;
    /**
     * <pre>
     * boolean类型
     * </pre>
     *
     * <code>bool age = 4;</code>
     * @return The age.
     */
    @java.lang.Override
    public boolean getAge() {
      return age_;
    }
    /**
     * <pre>
     * boolean类型
     * </pre>
     *
     * <code>bool age = 4;</code>
     * @param value The age to set.
     */
    private void setAge(boolean value) {
      
      age_ = value;
    }
    /**
     * <pre>
     * boolean类型
     * </pre>
     *
     * <code>bool age = 4;</code>
     */
    private void clearAge() {
      
      age_ = false;
    }

    public static final int STUDENT_NAME_FIELD_NUMBER = 5;
    private double studentName_;
    /**
     * <pre>
     * double类型
     * </pre>
     *
     * <code>double student_name = 5;</code>
     * @return The studentName.
     */
    @java.lang.Override
    public double getStudentName() {
      return studentName_;
    }
    /**
     * <pre>
     * double类型
     * </pre>
     *
     * <code>double student_name = 5;</code>
     * @param value The studentName to set.
     */
    private void setStudentName(double value) {
      
      studentName_ = value;
    }
    /**
     * <pre>
     * double类型
     * </pre>
     *
     * <code>double student_name = 5;</code>
     */
    private void clearStudentName() {
      
      studentName_ = 0D;
    }

    public static final int STUDENT_FS_FIELD_NUMBER = 6;
    private float studentFs_;
    /**
     * <pre>
     * float类型
     * </pre>
     *
     * <code>float student_fs = 6;</code>
     * @return The studentFs.
     */
    @java.lang.Override
    public float getStudentFs() {
      return studentFs_;
    }
    /**
     * <pre>
     * float类型
     * </pre>
     *
     * <code>float student_fs = 6;</code>
     * @param value The studentFs to set.
     */
    private void setStudentFs(float value) {
      
      studentFs_ = value;
    }
    /**
     * <pre>
     * float类型
     * </pre>
     *
     * <code>float student_fs = 6;</code>
     */
    private void clearStudentFs() {
      
      studentFs_ = 0F;
    }

    public static final int STUDENT_FS_DD_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString studentFsDd_;
    /**
     * <pre>
     * bytes类型
     * </pre>
     *
     * <code>bytes student_fs_dd = 7;</code>
     * @return The studentFsDd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStudentFsDd() {
      return studentFsDd_;
    }
    /**
     * <pre>
     * bytes类型
     * </pre>
     *
     * <code>bytes student_fs_dd = 7;</code>
     * @param value The studentFsDd to set.
     */
    private void setStudentFsDd(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentFsDd_ = value;
    }
    /**
     * <pre>
     * bytes类型
     * </pre>
     *
     * <code>bytes student_fs_dd = 7;</code>
     */
    private void clearStudentFsDd() {
      
      studentFsDd_ = getDefaultInstance().getStudentFsDd();
    }

    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.projectdemo.protobuf.UserPrefs.UserPreferences prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * 格式：字段类型 + 字段名称 + 字段编号 = 编号（唯一）
     * </pre>
     *
     * Protobuf type {@code UserPreferences}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.projectdemo.protobuf.UserPrefs.UserPreferences, Builder> implements
        // @@protoc_insertion_point(builder_implements:UserPreferences)
        com.example.projectdemo.protobuf.UserPrefs.UserPreferencesOrBuilder {
      // Construct using com.example.projectdemo.protobuf.UserPrefs.UserPreferences.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * String类型
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return The query.
       */
      @java.lang.Override
      public java.lang.String getQuery() {
        return instance.getQuery();
      }
      /**
       * <pre>
       * String类型
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return The bytes for query.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getQueryBytes() {
        return instance.getQueryBytes();
      }
      /**
       * <pre>
       * String类型
       * </pre>
       *
       * <code>string query = 1;</code>
       * @param value The query to set.
       * @return This builder for chaining.
       */
      public Builder setQuery(
          java.lang.String value) {
        copyOnWrite();
        instance.setQuery(value);
        return this;
      }
      /**
       * <pre>
       * String类型
       * </pre>
       *
       * <code>string query = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuery() {
        copyOnWrite();
        instance.clearQuery();
        return this;
      }
      /**
       * <pre>
       * String类型
       * </pre>
       *
       * <code>string query = 1;</code>
       * @param value The bytes for query to set.
       * @return This builder for chaining.
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setQueryBytes(value);
        return this;
      }

      /**
       * <pre>
       * int类型 sint32
       * </pre>
       *
       * <code>int32 page_number = 2;</code>
       * @return The pageNumber.
       */
      @java.lang.Override
      public int getPageNumber() {
        return instance.getPageNumber();
      }
      /**
       * <pre>
       * int类型 sint32
       * </pre>
       *
       * <code>int32 page_number = 2;</code>
       * @param value The pageNumber to set.
       * @return This builder for chaining.
       */
      public Builder setPageNumber(int value) {
        copyOnWrite();
        instance.setPageNumber(value);
        return this;
      }
      /**
       * <pre>
       * int类型 sint32
       * </pre>
       *
       * <code>int32 page_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPageNumber() {
        copyOnWrite();
        instance.clearPageNumber();
        return this;
      }

      /**
       * <pre>
       * long类型 sint64
       * </pre>
       *
       * <code>int64 result_per_page = 3;</code>
       * @return The resultPerPage.
       */
      @java.lang.Override
      public long getResultPerPage() {
        return instance.getResultPerPage();
      }
      /**
       * <pre>
       * long类型 sint64
       * </pre>
       *
       * <code>int64 result_per_page = 3;</code>
       * @param value The resultPerPage to set.
       * @return This builder for chaining.
       */
      public Builder setResultPerPage(long value) {
        copyOnWrite();
        instance.setResultPerPage(value);
        return this;
      }
      /**
       * <pre>
       * long类型 sint64
       * </pre>
       *
       * <code>int64 result_per_page = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResultPerPage() {
        copyOnWrite();
        instance.clearResultPerPage();
        return this;
      }

      /**
       * <pre>
       * boolean类型
       * </pre>
       *
       * <code>bool age = 4;</code>
       * @return The age.
       */
      @java.lang.Override
      public boolean getAge() {
        return instance.getAge();
      }
      /**
       * <pre>
       * boolean类型
       * </pre>
       *
       * <code>bool age = 4;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(boolean value) {
        copyOnWrite();
        instance.setAge(value);
        return this;
      }
      /**
       * <pre>
       * boolean类型
       * </pre>
       *
       * <code>bool age = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        copyOnWrite();
        instance.clearAge();
        return this;
      }

      /**
       * <pre>
       * double类型
       * </pre>
       *
       * <code>double student_name = 5;</code>
       * @return The studentName.
       */
      @java.lang.Override
      public double getStudentName() {
        return instance.getStudentName();
      }
      /**
       * <pre>
       * double类型
       * </pre>
       *
       * <code>double student_name = 5;</code>
       * @param value The studentName to set.
       * @return This builder for chaining.
       */
      public Builder setStudentName(double value) {
        copyOnWrite();
        instance.setStudentName(value);
        return this;
      }
      /**
       * <pre>
       * double类型
       * </pre>
       *
       * <code>double student_name = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStudentName() {
        copyOnWrite();
        instance.clearStudentName();
        return this;
      }

      /**
       * <pre>
       * float类型
       * </pre>
       *
       * <code>float student_fs = 6;</code>
       * @return The studentFs.
       */
      @java.lang.Override
      public float getStudentFs() {
        return instance.getStudentFs();
      }
      /**
       * <pre>
       * float类型
       * </pre>
       *
       * <code>float student_fs = 6;</code>
       * @param value The studentFs to set.
       * @return This builder for chaining.
       */
      public Builder setStudentFs(float value) {
        copyOnWrite();
        instance.setStudentFs(value);
        return this;
      }
      /**
       * <pre>
       * float类型
       * </pre>
       *
       * <code>float student_fs = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStudentFs() {
        copyOnWrite();
        instance.clearStudentFs();
        return this;
      }

      /**
       * <pre>
       * bytes类型
       * </pre>
       *
       * <code>bytes student_fs_dd = 7;</code>
       * @return The studentFsDd.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getStudentFsDd() {
        return instance.getStudentFsDd();
      }
      /**
       * <pre>
       * bytes类型
       * </pre>
       *
       * <code>bytes student_fs_dd = 7;</code>
       * @param value The studentFsDd to set.
       * @return This builder for chaining.
       */
      public Builder setStudentFsDd(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStudentFsDd(value);
        return this;
      }
      /**
       * <pre>
       * bytes类型
       * </pre>
       *
       * <code>bytes student_fs_dd = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStudentFsDd() {
        copyOnWrite();
        instance.clearStudentFsDd();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserPreferences)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.projectdemo.protobuf.UserPrefs.UserPreferences();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "query_",
              "pageNumber_",
              "resultPerPage_",
              "age_",
              "studentName_",
              "studentFs_",
              "studentFsDd_",
            };
            java.lang.String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\u0002\u0004\u0007\u0005\u0000\u0006\u0001\u0007\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.projectdemo.protobuf.UserPrefs.UserPreferences> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.projectdemo.protobuf.UserPrefs.UserPreferences.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.projectdemo.protobuf.UserPrefs.UserPreferences>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:UserPreferences)
    private static final com.example.projectdemo.protobuf.UserPrefs.UserPreferences DEFAULT_INSTANCE;
    static {
      UserPreferences defaultInstance = new UserPreferences();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserPreferences.class, defaultInstance);
    }

    public static com.example.projectdemo.protobuf.UserPrefs.UserPreferences getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserPreferences> PARSER;

    public static com.google.protobuf.Parser<UserPreferences> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
